package XmlWeb.repository;

import XmlWeb.model.Smestaj;
import XmlWeb.model.Enums.DodatneUsluge;
import XmlWeb.model.Enums.KategorijaSmestaja;
import XmlWeb.model.Enums.TipSmestaja;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

public interface SmestajRepository extends JpaRepository<Smestaj, Long> {
	
	
	
	@Query(value="SELECT DISTINCT SMESTAJ.ID, SMESTAJ.ADRESA, SMESTAJ.BROJ_OCENA, SMESTAJ.DRZAVA, SMESTAJ.GMAP_URL, SMESTAJ.GRAD, SMESTAJ.NAZIV, SMESTAJ.OPIS, SMESTAJ.REJTING, SMESTAJ.ZVEZDICE, SMESTAJ.TIP_ID, SMESTAJ.VLASNIK_ID"
			+ "FROM SMESTAJ, SMESTAJ_SOBE, SOBA "
			+ "WHERE SMESTAJ.ID=SMESTAJ_SOBE.SMESTAJ_ID AND SOBA.ID=SMESTAJ_SOBE.SOBE_ID AND "
			+ "UPPER(SMESTAJ.NAZIV)=UPPER(?1) AND SOBA.BROJ_LEZAJA>=?2"
			, nativeQuery = true)
	List<Smestaj> findByNameAndSobaNumberSeats(String name, int size);
	
	@Query(value="SELECT DISTINCT SMESTAJ.ID, SMESTAJ.ADRESA, SMESTAJ.BROJ_OCENA, SMESTAJ.DRZAVA, SMESTAJ.GMAP_URL, SMESTAJ.GRAD, SMESTAJ.NAZIV, SMESTAJ.OPIS, SMESTAJ.REJTING, SMESTAJ.ZVEZDICE, SMESTAJ.TIP_ID, SMESTAJ.VLASNIK_ID"
			+ "FROM SMESTAJ, SMESTAJ_SOBE, SOBA "
			+ "WHERE SMESTAJ.ID=SMESTAJ_SOBE.SMESTAJ_ID AND SOBA.ID=SMESTAJ_SOBE.SOBE_ID AND "
			+ "UPPER(SMESTAJ.NAZIV)=UPPER(?1) AND SOBA.BROJ_LEZAJA>=?2 AND SMESTAJ.ZVEZDICE = ?3"
			, nativeQuery = true)
	List<Smestaj> findByNameAndSobaNumberSeatsAndCategory(String name, int size, int category);
	
	/*
	FUCKING SHIT
	@Query(value = "SELECT DISTINCT SMESTAJ.ID, SMESTAJ.ADRESA\n, SMESTAJ.BROJ_OCENA, "
			+ "SMESTAJ.DRZAVA, SMESTAJ.GMAP_URL, SMESTAJ.GRAD, SMESTAJ.NAZIV, SMESTAJ.OPIS, SMESTAJ.REJTING, SMESTAJ.ZVEZDICE, SMESTAJ.TIP_ID, SMESTAJ.VLASNIK_ID " + 
			"FROM SMESTAJ, SMESTAJ_SOBE, SOBA, SOBA_IZNAJMLJIVANJA, IZNAJMLJIVANJE, REZERVACIJA \n" + 
			"WHERE REZERVACIJA.SOBA_ID=SOBA.ID AND SMESTAJ.ID=SMESTAJ_SOBE.SMESTAJ_ID AND SOBA.ID=SMESTAJ_SOBE.SOBE_ID AND SOBA_IZNAJMLJIVANJA.SOBA_ID=SOBA.ID AND SOBA_IZNAJMLJIVANJA.IZNAJMLJIVANJA_ID=IZNAJMLJIVANJE.ID AND "
			+ ""	+ 
			"((UPPER(SMESTAJ.NAZIV)=UPPER(?3) AND SOBA.BROJ_LEZAJA>=?4 AND IZNAJMLJIVANJE.DATUM_DO>=?1 AND IZNAJMLJIVANJE.DATUM_OD <=?2 AND IZNAJMLJIVANJE.MOZE_POJEDINACNO=true)"
			+ "OR(UPPER(SMESTAJ.NAZIV)=UPPER(?3) AND SOBA.BROJ_LEZAJA>=?4 AND IZNAJMLJIVANJE.DATUM_DO=?1 AND IZNAJMLJIVANJE.DATUM_OD =?2 AND IZNAJMLJIVANJE.MOZE_POJEDINACNO=false))", nativeQuery = true)
	List<Smestaj> findSimpleSearch(Date from, Date to, String name, int size);
	
	@Query(value = "SELECT DISTINCT SMESTAJ.ID, SMESTAJ.ADRESA\n, SMESTAJ.BROJ_OCENA, SMESTAJ.DRZAVA, SMESTAJ.GMAP_URL, SMESTAJ.GRAD, SMESTAJ.NAZIV, SMESTAJ.OPIS, SMESTAJ.REJTING, SMESTAJ.ZVEZDICE, SMESTAJ.TIP_ID, SMESTAJ.VLASNIK_ID " + 
			"FROM SMESTAJ, SMESTAJ_SOBE, SOBA, SOBA_IZNAJMLJIVANJA, IZNAJMLJIVANJE\n" + 
			"WHERE SMESTAJ.ID=SMESTAJ_SOBE.SMESTAJ_ID AND SOBA.ID=SMESTAJ_SOBE.SOBE_ID AND SOBA_IZNAJMLJIVANJA.SOBA_ID=SOBA.ID AND SOBA_IZNAJMLJIVANJA.IZNAJMLJIVANJA_ID=IZNAJMLJIVANJE.ID AND "	+ 
			"((UPPER(SMESTAJ.NAZIV)=UPPER(?3) AND SOBA.BROJ_LEZAJA>=?4 AND IZNAJMLJIVANJE.DATUM_DO>=?1 AND IZNAJMLJIVANJE.DATUM_OD <=?2 AND IZNAJMLJIVANJE.MOZE_POJEDINACNO=true)"
			+ "OR(UPPER(SMESTAJ.NAZIV)=UPPER(?3) AND SOBA.BROJ_LEZAJA>=?4 AND IZNAJMLJIVANJE.DATUM_DO=?1 AND IZNAJMLJIVANJE.DATUM_OD =?2 AND IZNAJMLJIVANJE.MOZE_POJEDINACNO=false))", nativeQuery = true)
	List<Smestaj> findAdvancedSearch(Date from, Date to, String name, int size, ArrayList<TipSmestaja> tipovi, ArrayList<DodatneUsluge> usluge, ArrayList<KategorijaSmestaja> cat);
	*/
}
